version: '3.9'
services:
  orchestrator-service:
    build: ./apps/orchestrator-service
    ports:
      - '8000:8000'
  media-service:
    build: ./apps/media-service
    ports:
      - '8001:8001'
  catalog-service:
    build: ./apps/catalog-service
    ports:
      - '8002:8002'
